spring:
  datasource:
    druid:
      url: jdbc:mysql://101.132.39.8:3306/blog_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 1qaz2wsx
      stat-view-servlet:
        login-username: admin
        login-password: admin
